name: imc_calculo
description: "A new Flutter project."
publish_to: 'none'
version: 2.2.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imagens/imc.png"

flutter_launcher_name:
  name: "Cálculo IMC"

flutter:
  uses-material-design: true
